config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
  end

  def create
    if Task.create(task_params)
      flash[:notice] = "New task created succesfully"
      redirect_to tasks_path
    else
      flash[:error] = "An error has ocurred"
      redirect_to 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:notice] = "The task was updated!"
      redirect_to tasks_path
    else
      flash[:error] = "An error has ocurred"
      redirect_to edit_task_path(@task)
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    flash[:alert] = "The task was deleted"
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:description, :priority, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Amazing Todo App
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .content-page
      %h1.general-title="ToDos App"
      = yield

app/views/tasks/edit.html.haml
%h1= "Editing task"
%p= "Change the current data"
= form_with model: @task, url: task_path(@task), method: :patch, class: "form-style" do |form|
  %div
    = form.label :description
    = form.text_field :description
  %div
    = form.label :priority
    = form.select :priority, [['High', 'High'], ['Medium', 'Medium'], ['Low', 'Low']]
  = form.submit "Update!", class: "submit"
  = link_to "Back", tasks_path, class: "back-action"

app/views/tasks/index.html.haml
-if flash[:notice]
  .notice
    = flash[:notice]
-elsif flash[:alert]
  .alert
    = flash[:alert]

.new-task
  = button_to "New task", new_task_path, method: :get
.task-list
  %table
    %thead
      %tr
        %th="Description"
        %th="Priority"
        %th="Status"
        %th="Actions"
    %tbody
      -@tasks.each do |task|
        %tr{id: "task_#{task.id}"}
          %td=task.description
          %td=task.priority
          %td=task.status
          %td
            .actions
              -unless task.status.eql?("complete")
                = button_to "Complete", task_path(task), method: :patch,  params: { task: { status: "complete" }}, form_class: "complete"
                = button_to "Modify", edit_task_path(task), method: :get, form_class: "modify"
              = button_to "Delete", task_path(task), method: :delete, form_class: "delete"

app/views/tasks/new.html.haml
%h1= "New Task"
%p= "Fill the following fields to add a new task to list"
= form_with scope: :task, url: tasks_path do |form|
  %div
    = form.label :description
    = form.text_field :description
  %div
    = form.label :priority
    = form.select :priority, [['High', 1], ['Medium', 2], ['Low', 3]]
  = form.submit 'Save!'